create extension if not exists pgcrypto;

create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(),
  file_name text not null,
  import_type text not null check (import_type in (
    'usage_history', 'inventory', 'item_master', 'supplier_master',
    'purchase_order', 'goods_receipt', 'sales_order', 'business_event'
  )),
  import_mode text not null check (import_mode in ('append', 'upsert', 'replace')),
  total_rows integer not null default 0 check (total_rows >= 0),
  success_rows integer not null default 0 check (success_rows >= 0),
  warning_rows integer not null default 0 check (warning_rows >= 0),
  error_rows integer not null default 0 check (error_rows >= 0),
  status text not null default 'STAGED' check (status in (
    'STAGED', 'VALIDATING', 'VALIDATED', 'IMPORTING',
    'IMPORTED', 'FAILED', 'ROLLED_BACK'
  )),
  uploaded_by uuid not null references auth.users(id) on delete restrict,
  uploaded_at timestamptz not null default now(),
  imported_at timestamptz,
  forecast_stale boolean not null default false,
  data_snapshot_at timestamptz,
  replace_confirmed_at timestamptz,
  replace_confirmed_by uuid references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (success_rows + warning_rows + error_rows <= total_rows)
);

create table if not exists core.import_staging (
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null check (row_number > 0),
  source_data jsonb not null,
  normalized_data jsonb,
  validation_status text not null default 'PENDING'
    check (validation_status in ('PENDING', 'SUCCESS', 'WARNING', 'ERROR')),
  staged_at timestamptz not null default now(),
  primary key (batch_id, row_number)
);

create table if not exists core.validation_error (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null check (row_number > 0),
  field_name text not null,
  error_code text not null,
  error_message text not null,
  severity text not null check (severity in ('WARNING', 'ERROR')),
  original_value text,
  created_at timestamptz not null default now(),
  unique (batch_id, row_number, field_name, error_code)
);

create table if not exists core.column_mapping (
  import_type text not null check (import_type in (
    'usage_history', 'inventory', 'item_master', 'supplier_master',
    'purchase_order', 'goods_receipt', 'sales_order', 'business_event'
  )),
  source_header text not null,
  target_column text not null,
  confidence numeric(5,4),
  confirmed boolean not null default false,
  updated_by uuid references auth.users(id) on delete restrict,
  updated_at timestamptz not null default now(),
  primary key (import_type, source_header),
  check (confidence is null or confidence between 0 and 1)
);

create table if not exists core.import_backup (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  import_type text not null,
  record_key text not null,
  target_table text not null,
  before_data jsonb,
  action text not null check (action in ('INSERTED', 'UPDATED', 'DELETED')),
  restored_at timestamptz,
  created_at timestamptz not null default now(),
  unique (batch_id, target_table, record_key)
);

create index if not exists upload_batch_status_idx
on core.upload_batch(status, uploaded_at desc);

create index if not exists import_staging_batch_status_idx
on core.import_staging(batch_id, validation_status);

create index if not exists validation_error_batch_idx
on core.validation_error(batch_id, severity, row_number);

create index if not exists import_backup_batch_idx
on core.import_backup(batch_id, target_table, record_key);

create or replace function core.set_import_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists upload_batch_set_updated_at on core.upload_batch;
create trigger upload_batch_set_updated_at
before update on core.upload_batch
for each row execute function core.set_import_updated_at();

drop policy if exists upload_batch_authenticated_select on core.upload_batch;
create policy upload_batch_authenticated_select
on core.upload_batch for select to authenticated
using ((select core.is_admin()));

drop policy if exists upload_batch_admin_mutation on core.upload_batch;
create policy upload_batch_admin_mutation
on core.upload_batch for all to authenticated
using ((select core.is_admin()))
with check ((select core.is_admin()));

drop policy if exists import_staging_authenticated_select on core.import_staging;
create policy import_staging_authenticated_select
on core.import_staging for select to authenticated
using ((select core.is_admin()));

drop policy if exists import_staging_admin_mutation on core.import_staging;
create policy import_staging_admin_mutation
on core.import_staging for all to authenticated
using ((select core.is_admin()))
with check ((select core.is_admin()));

drop policy if exists validation_error_authenticated_select on core.validation_error;
create policy validation_error_authenticated_select
on core.validation_error for select to authenticated
using ((select core.is_admin()));

drop policy if exists validation_error_admin_mutation on core.validation_error;
create policy validation_error_admin_mutation
on core.validation_error for all to authenticated
using ((select core.is_admin()))
with check ((select core.is_admin()));

drop policy if exists column_mapping_authenticated_select on core.column_mapping;
create policy column_mapping_authenticated_select
on core.column_mapping for select to authenticated
using ((select core.is_admin()));

drop policy if exists column_mapping_admin_mutation on core.column_mapping;
create policy column_mapping_admin_mutation
on core.column_mapping for all to authenticated
using ((select core.is_admin()))
with check ((select core.is_admin()));

drop policy if exists import_backup_authenticated_select on core.import_backup;
create policy import_backup_authenticated_select
on core.import_backup for select to authenticated
using ((select core.is_admin()));

drop policy if exists import_backup_admin_mutation on core.import_backup;
create policy import_backup_admin_mutation
on core.import_backup for all to authenticated
using ((select core.is_admin()))
with check ((select core.is_admin()));

alter table core.upload_batch enable row level security;
alter table core.import_staging enable row level security;
alter table core.validation_error enable row level security;
alter table core.column_mapping enable row level security;
alter table core.import_backup enable row level security;

revoke all on schema core from anon;
revoke all on core.upload_batch, core.import_staging, core.validation_error,
  core.column_mapping, core.import_backup from anon;
revoke all on core.upload_batch, core.import_staging, core.validation_error,
  core.column_mapping, core.import_backup from authenticated;

grant usage on schema core to authenticated;
grant select, insert, update, delete
on core.upload_batch, core.import_staging, core.validation_error,
  core.column_mapping, core.import_backup
to authenticated;

revoke all on function core.set_import_updated_at() from public, anon, authenticated;

create or replace function core.import_approved_batch(target_batch_id uuid)
returns jsonb
language plpgsql
volatile
security definer
set search_path = pg_catalog, core, raw
as $$
declare
  actor_id uuid := (select auth.uid());
  batch_row core.upload_batch;
  stage_row record;
  before_data jsonb;
  table_name text;
  key_table_expr text;
  key_json_expr text;
  insert_columns text;
  select_columns text;
  record_key text;
  imported_count integer := 0;
begin
  if actor_id is null or not core.is_admin() then
    raise exception using errcode = '42501', message = '관리자 권한이 필요합니다.';
  end if;

  select * into batch_row
  from core.upload_batch
  where batch_id = target_batch_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = '업로드 batch를 찾을 수 없습니다.';
  end if;

  if batch_row.status <> 'VALIDATED' or batch_row.error_rows > 0 then
    raise exception using errcode = '42501', message = '검증이 완료된 오류 없는 batch만 Import할 수 있습니다.';
  end if;

  if batch_row.import_mode = 'replace' and batch_row.replace_confirmed_at is null then
    raise exception using errcode = '42501', message = 'replace Import는 사용자 확인이 필요합니다.';
  end if;

  if batch_row.import_type = 'usage_history' then
    table_name := 'usage_history';
    key_table_expr := 'coalesce(t.usage_id, '''')';
    key_json_expr := 'coalesce($1->>''usage_id'', '''')';
    insert_columns := 'usage_id, item_id, use_date, qty, warehouse, note';
    select_columns := 'r.usage_id, r.item_id, r.use_date, r.qty, r.warehouse, r.note';
  elsif batch_row.import_type = 'inventory' then
    table_name := 'inventory';
    key_table_expr := 'coalesce(t."품목코드", '''') || ''|'' || coalesce(t."창고", '''') || ''|'' || coalesce(t."기준일자", '''')';
    key_json_expr := 'coalesce($1->>''품목코드'', '''') || ''|'' || coalesce($1->>''창고'', '''') || ''|'' || coalesce($1->>''기준일자'', '''')';
    insert_columns := '"품목코드", "창고", "현재고", "기준일자", "안전재고"';
    select_columns := 'r."품목코드", r."창고", r."현재고", r."기준일자", r."안전재고"';
  elsif batch_row.import_type = 'item_master' then
    table_name := 'item_master';
    key_table_expr := 'coalesce(t."품목코드", '''')';
    key_json_expr := 'coalesce($1->>''품목코드'', '''')';
    insert_columns := '"품목코드", "품목명", "품목구분", "단위", "표준단가", "사용여부", supplier_id';
    select_columns := 'r."품목코드", r."품목명", r."품목구분", r."단위", r."표준단가", r."사용여부", r.supplier_id';
  elsif batch_row.import_type = 'supplier_master' then
    table_name := 'supplier_master';
    key_table_expr := 'coalesce(t."공급업체코드", '''')';
    key_json_expr := 'coalesce($1->>''공급업체코드'', '''')';
    insert_columns := '"공급업체코드", "공급업체명", "국가", "표준리드타임(일)", "담당자", "사용여부"';
    select_columns := 'r."공급업체코드", r."공급업체명", r."국가", r."표준리드타임(일)", r."담당자", r."사용여부"';
  elsif batch_row.import_type = 'purchase_order' then
    table_name := 'purchase_order';
    key_table_expr := 'coalesce(t."발주번호", '''')';
    key_json_expr := 'coalesce($1->>''발주번호'', '''')';
    insert_columns := '"발주번호", "발주일", "공급업체", "품목코드", "발주수량", "단가", "납기예정일", "발주담당"';
    select_columns := 'r."발주번호", r."발주일", r."공급업체", r."품목코드", r."발주수량", r."단가", r."납기예정일", r."발주담당"';
  elsif batch_row.import_type = 'goods_receipt' then
    table_name := 'goods_receipt';
    key_table_expr := 'coalesce(t."입고번호", '''')';
    key_json_expr := 'coalesce($1->>''입고번호'', '''')';
    insert_columns := '"입고번호", "발주번호", "품목코드", "입고수량", "입고일", "입고창고"';
    select_columns := 'r."입고번호", r."발주번호", r."품목코드", r."입고수량", r."입고일", r."입고창고"';
  elsif batch_row.import_type = 'sales_order' then
    table_name := 'sales_order';
    key_table_expr := 'coalesce(t.sales_order_id, '''')';
    key_json_expr := 'coalesce($1->>''sales_order_id'', '''')';
    insert_columns := 'sales_order_id, order_date, customer_id, item_id, quantity, need_date, status';
    select_columns := 'r.sales_order_id, r.order_date, r.customer_id, r.item_id, r.quantity, r.need_date, r.status';
  elsif batch_row.import_type = 'business_event' then
    table_name := 'business_event';
    key_table_expr := 'coalesce(t.event_id, '''')';
    key_json_expr := 'coalesce($1->>''event_id'', '''')';
    insert_columns := 'event_id, event_type, event_date, item_id, supplier_id, event_name, impact_factor, note';
    select_columns := 'r.event_id, r.event_type, r.event_date, r.item_id, r.supplier_id, r.event_name, r.impact_factor, r.note';
  else
    raise exception using errcode = '22023', message = '지원하지 않는 Import Type입니다.';
  end if;

  if batch_row.import_mode = 'replace' then
    execute format(
      'insert into core.import_backup (batch_id, import_type, record_key, target_table, before_data, action)
       select $1, $2, %s, $3, to_jsonb(t), ''DELETED'' from raw.%I t
       on conflict (batch_id, target_table, record_key) do nothing',
      key_table_expr, table_name
    ) using target_batch_id, batch_row.import_type, table_name;
    execute format('delete from raw.%I', table_name);
  end if;

  for stage_row in
    select normalized_data
    from core.import_staging
    where batch_id = target_batch_id
      and validation_status in ('SUCCESS', 'WARNING')
    order by row_number
  loop
    execute format('select %s', key_json_expr)
      into record_key
      using stage_row.normalized_data;

    if batch_row.import_mode = 'upsert' then
      execute format('select to_jsonb(t) from raw.%I t where %s = %s', table_name, key_table_expr, key_json_expr)
        into before_data
        using stage_row.normalized_data;
      if before_data is not null then
        insert into core.import_backup (batch_id, import_type, record_key, target_table, before_data, action)
        values (target_batch_id, batch_row.import_type, record_key, table_name, before_data, 'UPDATED')
        on conflict (batch_id, target_table, record_key) do nothing;
        execute format('delete from raw.%I t where %s = %s', table_name, key_table_expr, key_json_expr)
          using stage_row.normalized_data;
      end if;
    end if;

    execute format(
      'insert into raw.%I (%s, batch_id, source_type, loaded_at, source_record_id)
       select %s, $2, ''FILE_UPLOAD'', now(), $3
       from jsonb_populate_record(null::raw.%I, $1) r',
      table_name, insert_columns, select_columns, table_name
    ) using stage_row.normalized_data, target_batch_id, record_key;
    imported_count := imported_count + 1;
  end loop;

  update core.upload_batch
  set status = 'IMPORTED',
      imported_at = now(),
      data_snapshot_at = now(),
      forecast_stale = (batch_row.import_type in ('usage_history', 'sales_order')),
      updated_at = now()
  where batch_id = target_batch_id;

  return jsonb_build_object('batch_id', target_batch_id, 'imported_rows', imported_count, 'status', 'IMPORTED');
end;
$$;

create or replace function core.rollback_batch(target_batch_id uuid)
returns jsonb
language plpgsql
volatile
security definer
set search_path = pg_catalog, core, raw
as $$
declare
  actor_id uuid := (select auth.uid());
  batch_row core.upload_batch;
  backup_row record;
  table_name text;
  restored_count integer := 0;
begin
  if actor_id is null or not core.is_admin() then
    raise exception using errcode = '42501', message = '관리자 권한이 필요합니다.';
  end if;

  select * into batch_row
  from core.upload_batch
  where batch_id = target_batch_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = '업로드 batch를 찾을 수 없습니다.';
  end if;
  if batch_row.status <> 'IMPORTED' then
    raise exception using errcode = '42501', message = 'Import 완료 상태의 batch만 rollback할 수 있습니다.';
  end if;

  table_name := batch_row.import_type;
  execute format('delete from raw.%I where batch_id = $1', table_name) using target_batch_id;

  for backup_row in
    select target_table, before_data
    from core.import_backup
    where batch_id = target_batch_id
      and before_data is not null
      and restored_at is null
    order by id
  loop
    execute format(
      'insert into raw.%I select r.* from jsonb_populate_record(null::raw.%I, $1) r',
      backup_row.target_table, backup_row.target_table
    ) using backup_row.before_data;
    update core.import_backup
    set restored_at = now()
    where batch_id = target_batch_id
      and target_table = backup_row.target_table
      and before_data = backup_row.before_data;
    restored_count := restored_count + 1;
  end loop;

  update core.upload_batch
  set status = 'ROLLED_BACK', updated_at = now()
  where batch_id = target_batch_id;

  return jsonb_build_object('batch_id', target_batch_id, 'restored_rows', restored_count, 'status', 'ROLLED_BACK');
end;
$$;

grant execute on function core.import_approved_batch(uuid) to authenticated;
grant execute on function core.rollback_batch(uuid) to authenticated;
revoke all on function core.import_approved_batch(uuid) from public, anon;
revoke all on function core.rollback_batch(uuid) from public, anon;
