create schema if not exists core;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null default '',
  department text not null default '',
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

create index if not exists app_user_role_active_idx on core.app_user(role, active);
create index if not exists audit_log_target_idx on core.audit_log(target_type, target_id, at desc);

create or replace function core.set_app_user_updated_at()
returns trigger language plpgsql security invoker set search_path = pg_catalog as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists app_user_set_updated_at on core.app_user;
create trigger app_user_set_updated_at before update on core.app_user for each row execute function core.set_app_user_updated_at();

create or replace function core.handle_new_auth_user()
returns trigger language plpgsql security definer set search_path = pg_catalog, core as $$
begin
  insert into core.app_user (user_id, email, name, department)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data ->> 'name', ''), coalesce(new.raw_user_meta_data ->> 'department', ''))
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function core.handle_new_auth_user();

create or replace function core.is_admin()
returns boolean language sql stable security definer set search_path = pg_catalog, core as $$
  select exists (select 1 from core.app_user where user_id = (select auth.uid()) and role = 'ADMIN' and active = true);
$$;

create or replace function core.admin_update_user(target_user_id uuid, next_role text, next_active boolean)
returns core.app_user language plpgsql volatile security definer set search_path = pg_catalog, core as $$
declare
  actor_id uuid := (select auth.uid());
  before_row core.app_user;
  after_row core.app_user;
begin
  if actor_id is null or not core.is_admin() then raise exception using errcode = '42501', message = '관리자 권한이 필요합니다.'; end if;
  if next_role not in ('ADMIN', 'USER') then raise exception using errcode = '22023', message = '올바르지 않은 role입니다.'; end if;
  if target_user_id = actor_id and (next_role <> 'ADMIN' or next_active = false) then raise exception using errcode = '42501', message = '자신의 관리자 권한과 활성 상태는 변경할 수 없습니다.'; end if;
  select * into before_row from core.app_user where user_id = target_user_id for update;
  if not found then raise exception using errcode = 'P0002', message = '사용자를 찾을 수 없습니다.'; end if;
  update core.app_user set role = next_role, active = next_active where user_id = target_user_id returning * into after_row;
  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (actor_id, case when before_row.role <> after_row.role then 'USER_ROLE_CHANGED' else 'USER_ACTIVE_CHANGED' end, 'app_user', target_user_id::text, to_jsonb(before_row), to_jsonb(after_row));
  return after_row;
end;
$$;

create or replace function core.record_login()
returns void language plpgsql volatile security definer set search_path = pg_catalog, core as $$
begin
  update core.app_user set last_login_at = now() where user_id = (select auth.uid()) and active = true;
end;
$$;

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;
alter table core.leadtime_plan enable row level security;
alter table core.usage_profile enable row level security;

drop policy if exists app_user_select_own_or_admin on core.app_user;
create policy app_user_select_own_or_admin on core.app_user for select to authenticated using ((select auth.uid()) = user_id or (select core.is_admin()));
drop policy if exists app_user_admin_update on core.app_user;
create policy app_user_admin_update on core.app_user for update to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));
drop policy if exists audit_log_admin_select on core.audit_log;
create policy audit_log_admin_select on core.audit_log for select to authenticated using ((select core.is_admin()));
drop policy if exists leadtime_plan_authenticated_select on core.leadtime_plan;
create policy leadtime_plan_authenticated_select on core.leadtime_plan for select to authenticated using (true);
drop policy if exists leadtime_plan_admin_mutation on core.leadtime_plan;
create policy leadtime_plan_admin_mutation on core.leadtime_plan for all to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));
drop policy if exists usage_profile_authenticated_select on core.usage_profile;
create policy usage_profile_authenticated_select on core.usage_profile for select to authenticated using (true);
drop policy if exists usage_profile_admin_mutation on core.usage_profile;
create policy usage_profile_admin_mutation on core.usage_profile for all to authenticated using ((select core.is_admin())) with check ((select core.is_admin()));

revoke all on schema core from anon;
revoke all on all tables in schema core from anon;
revoke insert, update, delete, truncate, references, trigger on all tables in schema core from authenticated;
grant usage on schema core to authenticated;
grant select on all tables in schema core to authenticated;
grant execute on function core.is_admin() to authenticated;
grant execute on function core.admin_update_user(uuid, text, boolean) to authenticated;
grant execute on function core.record_login() to authenticated;
revoke all on function core.is_admin() from public, anon;
revoke all on function core.admin_update_user(uuid, text, boolean) from public, anon;
revoke all on function core.record_login() from public, anon;
revoke insert, update, delete on core.audit_log from public, anon, authenticated;
revoke usage on schema analytics from anon;
revoke all on all tables in schema analytics from anon;
grant usage on schema analytics to authenticated;
grant select on all tables in schema analytics to authenticated;

-- 기존 월간 발주계획 테이블도 인증 계층 밖에서 접근할 수 없도록 잠급니다.
revoke all on all tables in schema public from anon;
grant select on all tables in schema public to authenticated;
revoke insert, update, delete, truncate, references, trigger on all tables in schema public from authenticated;

alter table if exists public.planning_runs enable row level security;
alter table if exists public.ol_demand enable row level security;
alter table if exists public.sfdc_pipeline enable row level security;
alter table if exists public.bulk_deals enable row level security;
alter table if exists public.historical_actuals enable row level security;
alter table if exists public.demand_confirmations enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array['planning_runs', 'ol_demand', 'sfdc_pipeline', 'bulk_deals', 'historical_actuals', 'demand_confirmations'] loop
    execute format('drop policy if exists %I on public.%I', 'authenticated_select_' || table_name, table_name);
    execute format('create policy %I on public.%I for select to authenticated using (true)', 'authenticated_select_' || table_name, table_name);
    execute format('drop policy if exists %I on public.%I', 'admin_mutation_' || table_name, table_name);
    execute format('create policy %I on public.%I for all to authenticated using ((select core.is_admin())) with check ((select core.is_admin()))', 'admin_mutation_' || table_name, table_name);
  end loop;
end;
$$;
